Upgrade to db-4.3.14 internal.
CVS patchset: 7473
CVS date: 2004/10/16 12:50:52

diff --git a/db/dist/configure b/db/dist/configure
--- a/db/dist/configure
+++ b/db/dist/configure
@@ -2154,11 +2154,11 @@ fi
 
 # Uniquename excludes C++, Java, RPC.
 if test "$db_cv_uniquename" = "yes"; then
-	if test "$db_cv_rpc" = "yes"; then
-		{ { echo "$as_me:$LINENO: error: --with-uniquename is not compatible with --enable-rpc" >&5
-echo "$as_me: error: --with-uniquename is not compatible with --enable-rpc" >&2;}
-   { (exit 1); exit 1; }; }
-	fi
+#	if test "$db_cv_rpc" = "yes"; then
+#		{ { echo "$as_me:$LINENO: error: --with-uniquename is not compatible with --enable-rpc" >&5
+#echo "$as_me: error: --with-uniquename is not compatible with --enable-rpc" >&2;}
+#   { (exit 1); exit 1; }; }
+#	fi
 	if test "$db_cv_cxx" = "yes"; then
 		{ { echo "$as_me:$LINENO: error: --with-uniquename is not compatible with --enable-cxx" >&5
 echo "$as_me: error: --with-uniquename is not compatible with --enable-cxx" >&2;}
