Update to 0.24.7.
CVS patchset: 7522
CVS date: 2004/10/29 13:34:35

diff --git a/neon/Makefile.in b/neon/Makefile.in
--- a/neon/Makefile.in
+++ b/neon/Makefile.in
@@ -1,80 +1,158 @@
+# Copyright (C) 2001-2004 Joe Orton <joe@manyfish.co.uk>
+# Copyright (C) 1994, 1995-8, 1999, 2000 Free Software Foundation, Inc.
+# This Makefile.in is free software; the Free Software Foundation
+# gives unlimited permission to copy and/or distribute it,
+# with or without modifications, as long as this notice is preserved.
 
-CFLAGS = -Ilib -I. -Isrc @CFLAGS@ @DEFS@
-LDFLAGS = -L. @LDFLAGS@
-LIBS = @LIBS@
-CC = @CC@
-INSTALL_PROGRAM = @INSTALL_PROGRAM@
-INSTALL_DATA = @INSTALL_DATA@
-INSTALL = @INSTALL@
-AR = ar
-RANLIB = @RANLIB@
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
+# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
+# PARTICULAR PURPOSE.
+
+# libtool bits mostly stolen from libxml and libtool/demo
+
+SHELL = @SHELL@
 
 prefix = @prefix@
 exec_prefix = @exec_prefix@
 bindir = @bindir@
 libdir = @libdir@
-man1dir = @mandir@/man1
-# Hmmmmm... the i18n stuff seems to want this:
-datadir = $(prefix)/@DATADIRNAME@
-# Previously I had:
-# datadir = @datadir@/sitecopy
-docdir = $(prefix)/doc/sitecopy
-sc_datadir = $(datadir)/sitecopy
+mandir = @mandir@
+man1dir = $(mandir)/man1
+man3dir = $(mandir)/man3
+datadir = @datadir@
+docdir = $(datadir)/doc/neon-@NEON_VERSION@
 includedir = @includedir@
-neonincludes = $(includedir)/libneon
+neonincludes = $(includedir)/neon
+pkgconfigdir = $(libdir)/pkgconfig
 
 top_srcdir = @top_srcdir@
-# Where does top_builddir come from?
-top_builddir = @top_srcdir@
+top_builddir = .
 srcdir = @srcdir@
-# intl stuff
-localedir = $(datadir)/locale
-gnulocaledir = $(prefix)/share/locale
-gettextsrcdir = $(prefix)/share/gettext
-aliaspath = $(localedir):.
+VPATH = @srcdir@
+
 @SET_MAKE@
 
-OBJECTS = src/http_request.o src/http_basic.o src/dav_basic.o src/dav_207.o \
-	src/string_utils.o src/dates.o src/xalloc.o src/hip_xml.o \
-	src/base64.o src/md5.o src/http_utils.o	src/uri.o src/socket.o \
-	src/http_auth.o
+LDFLAGS = -L. @LDFLAGS@
+LIBS = @LIBS@
+CC = @CC@
+INSTALL_PROGRAM = @INSTALL_PROGRAM@
+INSTALL_DATA = @INSTALL_DATA@
+INSTALL_SCRIPT = @INSTALL_SCRIPT@
+INSTALL = @INSTALL@
+transform = @program_transform_name@
 
-DIST_HEADERS = http_request.h http_utils.h uri.h socket.h http_basic.h \
-	 dav_basic.h dav_207.h dav_props.h hip_xml.h dates.h string_utils.h
+LIBTOOL = @LIBTOOL@
 
-libneon.a: $(OBJECTS)
-	$(AR) cru $@ $(OBJECTS)
-	$(RANLIB) $@
+XMLTO = xmlto
 
-shared: libneon.so
+# The headers to distribute - making up the public interface of neon
+DIST_HEADERS = ne_request.h ne_session.h ne_utils.h ne_uri.h ne_socket.h  \
+	ne_basic.h ne_207.h ne_props.h ne_xml.h ne_dates.h ne_string.h	  \
+	ne_cookies.h ne_defs.h ne_locks.h ne_alloc.h ne_md5.h ne_i18n.h \
+	ne_redirect.h ne_auth.h ne_compress.h ne_acl.h ne_ssl.h
 
-libneon.so: $(OBJECTS)
-	gcc -shared -o $@ $(OBJECTS)
+all: subdirs
 
-examples: nget
+check: subdirs
+	cd test && $(MAKE) check
 
-nget: libneon.a example/nget.o lib/basename.o
-	$(CC) $(LDFLAGS) -o $@  example/nget.o lib/basename.o -lneon
+# Useful for doing coverage analysis; use e.g.:
+#   make TESTS=string-tests MODULE=ne_string cover
+cover: subdirs
+	rm -f src/$(MODULE).da
+	cd test && $(MAKE) check
+	cd src; gcov -cb $(MODULE)
 
-install: install-static install-headers
+subdirs:
+	cd src && $(MAKE)
+	@echo
+	@echo "  Compilation complete. Run '$(MAKE) install' (as root?) to install neon."
+	@echo
 
-install-static: libneon.a
-	$(INSTALL) -d $(libdir)
-	cp libneon.a $(libdir)/libneon.a
+# Uses Tim Waugh's excellent "xmlto" utility, see
+# http://cyberelk.net/tim/xmlto/.  (The docs target is executed at release
+# time before generating a .tar.gz)
+docs: docs-man docs-html
 
-install-shared: libneon.so
-	$(INSTALL) -d $(libdir)
-	cp libneon.so $(libdir)/libneon.so
+docs-man:
+	rm -rf doc/man; mkdir doc/man
+	$(XMLTO) -o `pwd`/doc/man man doc/manual.xml
 
-install-headers:
-	$(INSTALL) -d $(neonincludes)
-	@for h in $(DIST_HEADERS); do \
-		echo Installing $$h into $(neonincludes); \
-		$(INSTALL_DATA) src/$$h $(neonincludes)/$$h; \
+docs-pdf:
+	$(XMLTO) -o `pwd`/doc pdf doc/manual.xml
+
+docs-ps:
+	$(XMLTO) -o `pwd`/doc ps doc/manual.xml
+
+docs-html:
+	test -d doc/html && rm -rf doc/html || true
+	mkdir doc/html
+	$(XMLTO) -o `pwd`/doc/html -x doc/html.xsl html doc/manual.xml
+
+# Validate the manual source
+docs-valid:
+	xmllint --noout --valid doc/manual.xml
+
+clean:
+	cd src && $(MAKE) clean
+	cd test && $(MAKE) clean
+
+distclean: clean
+	rm -rf Makefile config.h config.status libtool config.log config.cache neon-config autom4te.cache neon.pc test/Makefile test/common/Makefile src/Makefile
+
+again: clean
+
+Makefile: Makefile.in
+	@./config.status Makefile
+
+neon-config: neon-config.in
+	@./config.status neon-config
+
+install-docs: install-man install-html
+
+install-html:
+	$(INSTALL) -d $(DESTDIR)$(docdir)/html
+	for d in $(srcdir)/doc/html/*.html; do \
+		$(INSTALL_DATA) $$d $(DESTDIR)$(docdir)/html; \
 	done
 
-neon_dir = src
-config_h = config.h
+install-man:
+	$(INSTALL) -d $(DESTDIR)$(man3dir)
+	$(INSTALL) -d $(DESTDIR)$(man1dir)
+	for m in $(srcdir)/doc/man/*.3; do \
+	 $(INSTALL_DATA) $$m $(DESTDIR)$(man3dir); done
+	for m in $(srcdir)/doc/man/*.1; do \
+	 $(INSTALL_DATA) $$m $(DESTDIR)$(man1dir); done
 
-include src/Makefile.incl
+install: install-@ALLOW_INSTALL@
+
+install-memleak:
+	@echo "ERROR: The neon internal memory leak checking code is for testing"
+	@echo "ERROR: purposes only; this copy of neon must not be installed."
+	@false
+
+install-yes: install-lib install-headers install-config install-docs
+
+# libtool does all the necessary magic here
+install-lib: subdirs
+	$(INSTALL) -d $(DESTDIR)$(libdir)
+	$(LIBTOOL) --mode=install $(INSTALL) src/libneon.la \
+		$(DESTDIR)$(libdir)/libneon.la
+
+install-headers:
+	$(INSTALL) -d $(DESTDIR)$(neonincludes)
+	@for h in $(DIST_HEADERS); do \
+		echo Installing $$h into $(DESTDIR)$(neonincludes); \
+		$(INSTALL_DATA) $(srcdir)/src/$$h $(DESTDIR)$(neonincludes)/$$h \
+			|| exit 1; \
+	done
+
+install-config: neon-config neon.pc
+	$(INSTALL) -d $(DESTDIR)$(bindir)
+	@echo Installing neon-config into $(DESTDIR)$(bindir)
+	@$(INSTALL_SCRIPT) neon-config \
+		$(DESTDIR)$(bindir)/`echo neon-config|sed '$(transform)'`
+	$(INSTALL) -d $(DESTDIR)$(pkgconfigdir)
+	$(INSTALL_DATA) neon.pc $(DESTDIR)$(pkgconfigdir)/neon.pc
 
